version: '3.8'

services:
  apprenant-service:
    build: ./Application de gestion des competences (Partie 2)
    ports:
      - "5001:5001"
    env_file:
      - ./Application de gestion des competences (Partie 2)/.env
    depends_on:
      - mongo_apprenant
      - brief-service

  brief-service:
    build: ./brief-service
    ports:
      - "5000:5000"
    env_file:
      - ./brief-service/.env
    depends_on:
      - mongo_brief

  mongo_apprenant:
    image: mongo
    container_name: mongo_apprenant
    ports:
      - "27018:27017"

  mongo_brief:
    image: mongo
    container_name: mongo_brief
    ports:
      - "27017:27017"
